// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaLXrANizji4uU74knRudK7hAlOrt-Jfw',
    appId: '1:980690811295:web:1ce0edac8212fcf98225aa',
    messagingSenderId: '980690811295',
    projectId: 'webproject-48ca4',
    authDomain: 'webproject-48ca4.firebaseapp.com',
    storageBucket: 'webproject-48ca4.appspot.com',
    measurementId: 'G-MW3Z1TGMSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Tasv8GrCTKvcI6J3O8o9YPBnfcx34t4',
    appId: '1:980690811295:android:95d18d63ec31af558225aa',
    messagingSenderId: '980690811295',
    projectId: 'webproject-48ca4',
    storageBucket: 'webproject-48ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUR3PRm-spuxKgKqREWs4ZiaRTWoOgMM',
    appId: '1:980690811295:ios:d3a332d9e861bb178225aa',
    messagingSenderId: '980690811295',
    projectId: 'webproject-48ca4',
    storageBucket: 'webproject-48ca4.appspot.com',
    iosClientId: '980690811295-tsf31qe6t3qlvqrekob02hj1rhjfj8st.apps.googleusercontent.com',
    iosBundleId: 'com.squat.bettercoach.dev',
  );
}
